---
- hosts: all,!nagios,!webserver,!loadbalancer
  remote_user: ansible
  become: yes

  tasks:

  - name: Install EPEL package
    yum:
      name: epel-release
      state: latest
       
  
  - name: Install nagios client packages
    yum:
      pkg:
        - nrpe
        - nagios-plugins-all     
      state: latest
      update_cache: yes

  - name: Deploy Ansible client configuration file
    become: yes
    become_user: root
    copy:
      src:  /ansible/templates/nrpe.cfg.j2
      dest: /etc/nagios/nrpe.cfg   

  - name: Restart nrpe service
    service:
      name: nrpe
      state: restarted
      enabled: yes
