---
- hosts: webserver7
  remote_user: ansible
  become: yes

  tasks:
  - name: install latest apache
    yum:
      name: httpd
      state: latest

  - name: ensure apache server is running
    service:
      name: httpd
      state: started

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
